export const TYPES = {
    FETCH_CHANNELS_LOADING: 'FETCH_CHANNELS_LOADING',
    FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
    FETCH_CHANNELS_FAIL: 'FETCH_CHANNELS_FAIL',
    FETCH_PROGRAMS_BY_CHANNEL: 'FETCH_PROGRAMS_BY_CHANNEL',
    FETCH_PROGRAMS_BY_SUCCESS: 'FETCH_PROGRAMS_BY_SUCCESS',
    FETCH_PROGRAMS_BY_FAIL: 'FETCH_PROGRAMS_BY_FAIL',
    SET_TIME_LIST_HEADER: 'SET_TIME_LIST_HEADER',
    UPDATE_DATE_FETCH_MORE: 'UPDATE_DATE_FETCH_MORE'
}